use e_comarce;

-- 1)Query: Retrieve the total revenue generated by each product category.

 SELECT pc.CategoryName, SUM(p.Price * ci.Quantity) AS TotalRevenue
 FROM Product_Categories pc
 JOIN Products p ON pc.CategoryID = p.CategoryID
 JOIN Cart_Items ci ON p.ProductID = ci.ProductID
 GROUP BY pc.CategoryName;


-- 2)Query: Find the top 3 customers who have made the highest total purchases.

 SELECT u.Name AS CustomerName, SUM(t.TotalAmount) AS TotalPurchases
 FROM Users u
 JOIN Customers c ON u.UserID = c.UserID
 JOIN Transactions t ON c.CustomerID = t.CustomerID
 GROUP BY u.Name
 ORDER BY TotalPurchases DESC
 LIMIT 3;



-- 3)Query: Retrieve the most frequently purchased product by customers.

 SELECT p.Name AS MostFrequentProduct, COUNT(ci.CartItemID) AS PurchaseCount
 FROM Products p
 JOIN Cart_Items ci ON p.ProductID = ci.ProductID
 GROUP BY p.Name
 ORDER BY PurchaseCount DESC
 LIMIT 1;


-- 4)Query: Retrieve the total number of products in each product category.

 SELECT pc.CategoryName, COUNT(p.ProductID) AS ProductCount
 FROM Product_Categories pc
 LEFT JOIN Products p ON pc.CategoryID = p.CategoryID
 GROUP BY pc.CategoryName;


-- 5)Query: Retrieve the average price of products in each product category.

SELECT pc.CategoryName, AVG(p.Price) AS AveragePrice
FROM Product_Categories pc
LEFT JOIN Products p ON pc.CategoryID = p.CategoryID
GROUP BY pc.CategoryName;


